---
title: "Delitos de Costa Rica"
author: "Daniel Saravia Cruz"
format: 
 html:
  toc: true
  lang: es
---

# Presentación
Este documento presenta estadísticas de delitos cometidos en Cotsa Rica. Los datos provienen del [sitio de datos abiertos del Organismo de Investigación Judicial (OIJ)](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos).

# Carga y muestra de los datos 
```{r}
#| label: carga-muestra-datos
#| code-fold: true

delitos_2022 <- read.csv("estadisticaspoliciales2022.csv")

head(delitos_2022)
# Tabla con las 10 primeras filas y con columnas seleccionadas
knitr::kable(
	head(
		delitos_2022[, c("Delito", "SubDelito", "Fecha", "Victima", "Edad", "Provincia")], 
		15
	),
	caption = "Muestra de datos de delitos cometidos en 2022 en Costa Rica"
)

```
# Gráficos de delitos por provincia

## Barras verticales
```{r}
#| label: delitos-provincia-barras-verticales
#| code-fold: true

tabla_delitos <- table(delitos_2022$Provincia)
 
tabla_delitos_ordenada <- sort(tabla_delitos, decreasing = TRUE )

barplot(
  height = tabla_delitos_ordenada,
  main = 'Delitos cometidos en Costa Rica en 2022',
  Sub = "Fuente OIJ",
  cex.names = 0.5,
  cex.axis = 0.5, 
  col = "red",
  las = 2,
  )


```
## Barras horizontales
```{r}
tabla_delitos <- table(delitos_2022$Provincia)
 
tabla_delitos_ordenada <- sort(tabla_delitos, decreasing = TRUE)
# Gráfico de barras horizontales
barplot(
	height = tabla_delitos_ordenada,
	main = "Cantidad de delitos cometidos en 2022 por provincia", 
	sub = "Fuente: OIJ",
	col = "red",
	las = 2,
	cex.names = 0.5,
	cex.axis = 0.7,
	horiz = TRUE
)
```

### Pastel
```{r}
#| label: cantidad-delitos-provincia-pastel
#| code-fold: true
# Crear tabla de frecuencias
tabla_delitos <- table(delitos_2022$Provincia)
# Ordenar ascendentemente la tabla de frecuencia
tabla_delitos_ordenada <- sort(tabla_delitos)
# Gráfico de pastel
pie(
  tabla_delitos_ordenada,
  main = "Cantidad de delitos cometidos en 2022 por provincia",
  sub = "Fuente: OIJ",
  col = rainbow(length(tabla_delitos_ordenada)),
  cex = 0.8,
  labels = paste0(
  	round(100 * tabla_delitos_ordenada / sum(tabla_delitos_ordenada), 1), 
  	"%"
  )
  # agregar leyenda
  
)
```


## Gráficos de cantidad de delitos por cantón

### Barras verticales
```{r}
#| label: cantidad-delitos-cantones-barras-verticales
#| code-fold: true
# Crear tabla de frecuencias
tabla_delitos <- table(delitos_2022$Canton)
# Ordenar descendentemente la tabla de frecuencia
tabla_delitos_ordenada <- sort(tabla_delitos, decreasing = TRUE)
# Obtener los cantones con más delitos
tabla_delitos_ordenada <- head(tabla_delitos_ordenada, 20)
# Gráfico de barras verticales
barplot(
	height = tabla_delitos_ordenada,
	main = "Cantidad de delitos cometidos en 2022 por cantón", 
	sub = "Fuente: OIJ",
	col = "blue",
	las = 2, # inclinación de las etiquetas (valor entre 0 y 3)
	cex.names = 0.5,  # tamaño de las etiquetas
	cex.axis = 0.7 # tamaño de los números en el eje 
)
```
